package com.yizhaoqi.smartpai.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.yizhaoqi.smartpai.exception.RateLimitExceededException;
import com.yizhaoqi.smartpai.model.User;
import com.yizhaoqi.smartpai.repository.UserRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor;
import org.springframework.stereotype.Service;
import org.springframework.web.socket.TextMessage;
import org.springframework.web.socket.WebSocketSession;

import java.time.Duration;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.RejectedExecutionException;

/**
 * 聊天处理服务
 * 负责处理WebSocket聊天消息和管理对话历史
 * 
 * @author Generated by Assistant
 */
@Service
public class ChatHandler {
    
    private static final Logger logger = LoggerFactory.getLogger(ChatHandler.class);
    private static final int MAX_MATCHED_CHUNK_LEN = 800;
    private static final int MAX_EVIDENCE_SNIPPET_LEN = 160;
    private static final int VISIBLE_SOURCE_LIMIT = 3;
    private static final int STREAM_CHUNK_SIZE = 28;
    private static final long STREAM_CHUNK_DELAY_MS = 18L;
    private final RedisTemplate<String, String> redisTemplate;
    private final RagPythonClient ragPythonClient;
    private final UserRepository userRepository;
    private final OrgTagCacheService orgTagCacheService;
    private final RateLimitService rateLimitService;
    private final ThreadPoolTaskExecutor chatMonitorExecutor;
    private final ObjectMapper objectMapper;
    
    // 用于存储每个会话的完整响应
    private final Map<String, StringBuilder> responseBuilders = new ConcurrentHashMap<>();
    // 用于跟踪每个会话的响应完成状态
    private final Map<String, CompletableFuture<String>> responseFutures = new ConcurrentHashMap<>();
    // 停止标志 - 简单方案
    private final Map<String, Boolean> stopFlags = new ConcurrentHashMap<>();
    // 用于存储每个会话的引用映射：sessionId -> {referenceNumber -> detail}
    private final Map<String, Map<Integer, ReferenceInfo>> sessionReferenceMappings = new ConcurrentHashMap<>();

    public ChatHandler(RedisTemplate<String, String> redisTemplate,
                      RagPythonClient ragPythonClient,
                      UserRepository userRepository,
                      OrgTagCacheService orgTagCacheService,
                      RateLimitService rateLimitService,
                      @Qualifier("chatMonitorExecutor") ThreadPoolTaskExecutor chatMonitorExecutor) {
        this.redisTemplate = redisTemplate;
        this.ragPythonClient = ragPythonClient;
        this.userRepository = userRepository;
        this.orgTagCacheService = orgTagCacheService;
        this.rateLimitService = rateLimitService;
        this.chatMonitorExecutor = chatMonitorExecutor;
        this.objectMapper = new ObjectMapper();
    }

    public void processMessage(String userId, String userMessage, WebSocketSession session) {
        logger.info("开始处理消息，用户ID: {}, 会话ID: {}", userId, session.getId());
        try {
            rateLimitService.checkChatByUser(userId);

            // 1. 获取或创建会话 ID
            String conversationId = getOrCreateConversationId(userId);
            logger.info("会话ID: {}, 用户ID: {}", conversationId, userId);
            
            // 为当前会话创建响应构建器
            responseBuilders.put(session.getId(), new StringBuilder());
            // 创建一个CompletableFuture来跟踪响应完成状态
            CompletableFuture<String> responseFuture = new CompletableFuture<>();
            responseFutures.put(session.getId(), responseFuture);
            stopFlags.remove(session.getId());
            
            // 2. 获取对话历史
            List<Map<String, String>> history = getConversationHistory(conversationId);
            logger.debug("获取到 {} 条历史对话", history.size());

            submitRagQuery(userId, userMessage, conversationId, history, session, responseFuture);
            
        } catch (RateLimitExceededException e) {
            sendRateLimitMessage(session, e);
            cleanupSessionState(session.getId(), null);
        } catch (Exception e) {
            logger.error("处理消息错误: {}", e.getMessage(), e);
            handleError(session, e);
            cleanupSessionState(session.getId(), e);
        }
    }

    private void submitRagQuery(String userId, String userMessage, String conversationId,
                                List<Map<String, String>> history, WebSocketSession session,
                                CompletableFuture<String> responseFuture) {
        try {
            chatMonitorExecutor.execute(() -> {
                try {
                    User user = resolveUser(userId);
                    List<String> effectiveOrgTags = orgTagCacheService.getUserEffectiveOrgTags(user.getUsername());

                    Map<String, Object> payload = new LinkedHashMap<>();
                    payload.put("query", userMessage);
                    payload.put("topK", 5);
                    payload.put("chatId", conversationId);
                    payload.put("history", history);
                    payload.put("userId", String.valueOf(user.getId()));
                    payload.put("username", user.getUsername());
                    payload.put("role", user.getRole().name());
                    payload.put("allowedOrgTags", effectiveOrgTags);
                    payload.put("allowPublic", true);

                    logger.info("调用 Python RAG 生成回复: userId={}, conversationId={}", userId, conversationId);
                    Map<String, Object> ragResponse = ragPythonClient.query(payload);
                    String answer = stringValue(ragResponse.get("answer"));
                    List<Map<String, Object>> sources = extractSources(ragResponse.get("sources"));
                    Map<Integer, ReferenceInfo> referenceMapping = buildReferenceMappingFromSources(sources, userMessage);
                    sessionReferenceMappings.put(session.getId(), referenceMapping);

                    String completeResponse = appendCompactSourceLinks(answer, referenceMapping);
                    StringBuilder responseBuilder = responseBuilders.get(session.getId());
                    if (responseBuilder != null) {
                        responseBuilder.append(completeResponse);
                    }

                    if (!Boolean.TRUE.equals(stopFlags.get(session.getId()))) {
                        sendResponseChunks(session, completeResponse);
                        sendCompletionNotification(session);
                        updateConversationHistory(conversationId, userMessage, completeResponse, referenceMapping);
                        responseFuture.complete(completeResponse);
                    } else {
                        responseFuture.complete("");
                        logger.info("RAG 回复已生成但会话已停止，跳过发送与入库: sessionId={}", session.getId());
                    }

                    logger.info("消息处理完成，用户ID: {}", userId);
                    cleanupSessionState(session.getId(), null);
                } catch (Exception e) {
                    logger.error("Python RAG 聊天处理失败: {}", e.getMessage(), e);
                    handleError(session, e);
                    sendCompletionNotification(session);
                    cleanupSessionState(session.getId(), e);
                }
            });
        } catch (RejectedExecutionException ex) {
            logger.warn("聊天线程池已满，会话ID: {}", session.getId());
            handleError(session, new RuntimeException("系统繁忙，请稍后重试"));
            cleanupSessionState(session.getId(), ex);
        }
    }

    private void cleanupSessionState(String sessionId, Throwable throwable) {
        responseBuilders.remove(sessionId);
        CompletableFuture<String> future = responseFutures.remove(sessionId);
        if (throwable != null && future != null && !future.isDone()) {
            future.completeExceptionally(throwable);
        }
    }

    private String getOrCreateConversationId(String userId) {
        String key = "user:" + userId + ":current_conversation";
        String conversationId = redisTemplate.opsForValue().get(key);
        
        if (conversationId == null) {
            conversationId = UUID.randomUUID().toString();
            redisTemplate.opsForValue().set(key, conversationId, Duration.ofDays(7));
            logger.info("为用户 {} 创建新的会话ID: {}", userId, conversationId);
        } else {
            logger.info("获取到用户 {} 的现有会话ID: {}", userId, conversationId);
        }
        
        return conversationId;
    }

    private List<Map<String, String>> getConversationHistory(String conversationId) {
        List<Map<String, Object>> records = getConversationHistoryRecords(conversationId);
        List<Map<String, String>> history = new ArrayList<>();
        for (Map<String, Object> message : records) {
            Map<String, String> normalized = new HashMap<>();
            normalized.put("role", String.valueOf(message.getOrDefault("role", "")));
            normalized.put("content", String.valueOf(message.getOrDefault("content", "")));
            Object timestamp = message.get("timestamp");
            if (timestamp != null) {
                normalized.put("timestamp", String.valueOf(timestamp));
            }
            history.add(normalized);
        }
        return history;
    }

    private List<Map<String, Object>> getConversationHistoryRecords(String conversationId) {
        String key = "conversation:" + conversationId;
        String json = redisTemplate.opsForValue().get(key);
        try {
            if (json == null) {
                logger.debug("会话 {} 没有历史记录", conversationId);
                return new ArrayList<>();
            }

            List<Map<String, Object>> history = objectMapper.readValue(json, new TypeReference<List<Map<String, Object>>>() {});
            logger.debug("读取到会话 {} 的 {} 条历史记录", conversationId, history.size());
            return history;
        } catch (JsonProcessingException e) {
            logger.error("解析对话历史出错: {}, 会话ID: {}", e.getMessage(), conversationId, e);
            return new ArrayList<>();
        }
    }

    private void updateConversationHistory(String conversationId, String userMessage, String response,
                                           Map<Integer, ReferenceInfo> referenceMapping) {
        String key = "conversation:" + conversationId;
        List<Map<String, Object>> history = getConversationHistoryRecords(conversationId);
        
        // 获取当前时间戳
        String currentTimestamp = java.time.LocalDateTime.now().format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss"));
        
        // 添加用户消息（带时间戳）
        Map<String, Object> userMsgMap = new HashMap<>();
        userMsgMap.put("role", "user");
        userMsgMap.put("content", userMessage);
        userMsgMap.put("timestamp", currentTimestamp);
        history.add(userMsgMap);

        // 添加助手回复（带时间戳）
        Map<String, Object> assistantMsgMap = new HashMap<>();
        assistantMsgMap.put("role", "assistant");
        assistantMsgMap.put("content", response);
        assistantMsgMap.put("timestamp", currentTimestamp);
        if (referenceMapping != null && !referenceMapping.isEmpty()) {
            assistantMsgMap.put("referenceMappings", toSerializableReferenceMappings(referenceMapping));
        }
        history.add(assistantMsgMap);
        
        // 限制历史记录长度，保留最近的20条消息
        if (history.size() > 20) {
            history = history.subList(history.size() - 20, history.size());
        }
        
        try {
            String json = objectMapper.writeValueAsString(history);
            redisTemplate.opsForValue().set(key, json, Duration.ofDays(7));
            logger.debug("更新会话历史，会话ID: {}, 总消息数: {}", conversationId, history.size());
        } catch (JsonProcessingException e) {
            logger.error("序列化对话历史出错: {}, 会话ID: {}", e.getMessage(), conversationId, e);
        }
    }

    private Map<String, Map<String, Object>> toSerializableReferenceMappings(Map<Integer, ReferenceInfo> referenceMapping) {
        Map<String, Map<String, Object>> serialized = new HashMap<>();
        for (Map.Entry<Integer, ReferenceInfo> entry : referenceMapping.entrySet()) {
            ReferenceInfo detail = entry.getValue();
            Map<String, Object> item = new HashMap<>();
            item.put("fileMd5", detail.fileMd5());
            item.put("fileName", detail.fileName());
            item.put("pageNumber", detail.pageNumber());
            item.put("anchorText", detail.anchorText());
            item.put("retrievalMode", detail.retrievalMode());
            item.put("retrievalLabel", detail.retrievalLabel());
            item.put("retrievalQuery", detail.retrievalQuery());
            item.put("matchedChunkText", detail.matchedChunkText());
            item.put("evidenceSnippet", detail.evidenceSnippet());
            item.put("score", detail.score());
            item.put("chunkId", detail.chunkId());
            serialized.put(String.valueOf(entry.getKey()), item);
        }
        return serialized;
    }

    private User resolveUser(String userId) {
        try {
            return userRepository.findById(Long.parseLong(userId))
                    .orElseThrow(() -> new RuntimeException("用户不存在: " + userId));
        } catch (NumberFormatException ignored) {
            return userRepository.findByUsername(userId)
                    .orElseThrow(() -> new RuntimeException("用户不存在: " + userId));
        }
    }

    private List<Map<String, Object>> extractSources(Object rawSources) {
        if (!(rawSources instanceof List<?> sourceList)) {
            return Collections.emptyList();
        }

        List<Map<String, Object>> sources = new ArrayList<>();
        for (Object source : sourceList) {
            if (source instanceof Map<?, ?> sourceMap) {
                Map<String, Object> normalized = new HashMap<>();
                for (Map.Entry<?, ?> entry : sourceMap.entrySet()) {
                    if (entry.getKey() != null) {
                        normalized.put(String.valueOf(entry.getKey()), entry.getValue());
                    }
                }
                sources.add(normalized);
            }
        }
        return sources;
    }

    private Map<Integer, ReferenceInfo> buildReferenceMappingFromSources(List<Map<String, Object>> sources, String userMessage) {
        Map<Integer, ReferenceInfo> referenceMapping = new LinkedHashMap<>();
        int referenceNumber = 1;

        for (Map<String, Object> source : sources) {
            String fileMd5 = stringValue(source.get("fileMd5"));
            String fileName = stringValue(source.get("fileName"));
            if (fileMd5.isBlank() || fileName.isBlank()) {
                continue;
            }

            String anchorText = stringValue(source.get("anchorText"));
            String snippet = stringValue(source.get("snippet"));
            String matchedChunkText = trimToMaxLength(!snippet.isBlank() ? snippet : anchorText, MAX_MATCHED_CHUNK_LEN);
            Integer pageNumber = integerValue(source.get("pageNumber"));
            Integer chunkId = integerValue(source.get("chunkId"));
            Double score = doubleValue(source.get("score"));
            String retrievalMode = stringValue(source.get("retrievalMode"));
            if (retrievalMode.isBlank()) {
                retrievalMode = "VECTOR";
            }

            ReferenceInfo detail = new ReferenceInfo(
                    fileMd5,
                    fileName,
                    pageNumber,
                    anchorText,
                    retrievalMode,
                    buildRetrievalLabel(retrievalMode),
                    normalizeEvidenceText(userMessage),
                    matchedChunkText,
                    buildEvidenceSnippet(userMessage, anchorText, matchedChunkText),
                    score,
                    chunkId
            );
            referenceMapping.put(referenceNumber, detail);
            referenceNumber++;
        }

        return referenceMapping;
    }

    private String appendCompactSourceLinks(String answer, Map<Integer, ReferenceInfo> referenceMapping) {
        String normalizedAnswer = stringValue(answer);
        if (normalizedAnswer.isBlank()) {
            normalizedAnswer = "暂无相关信息。";
        }
        if (referenceMapping == null || referenceMapping.isEmpty()) {
            return normalizedAnswer;
        }

        StringBuilder builder = new StringBuilder(normalizedAnswer);
        builder.append("\n\n参考：");
        int visibleCount = 0;
        for (Map.Entry<Integer, ReferenceInfo> entry : referenceMapping.entrySet()) {
            if (visibleCount >= VISIBLE_SOURCE_LIMIT) {
                break;
            }
            ReferenceInfo detail = entry.getValue();
            if (visibleCount > 0) {
                builder.append("；");
            }
            builder.append("来源#").append(entry.getKey()).append(": ").append(detail.fileName());
            if (detail.pageNumber() != null && detail.pageNumber() > 0) {
                builder.append(" | 第").append(detail.pageNumber()).append("页");
            }
            visibleCount++;
        }
        return builder.toString().trim();
    }

    private String stringValue(Object value) {
        return value == null ? "" : String.valueOf(value).trim();
    }

    private Integer integerValue(Object value) {
        if (value == null) {
            return null;
        }
        if (value instanceof Number number) {
            return number.intValue();
        }
        try {
            return Integer.parseInt(String.valueOf(value));
        } catch (NumberFormatException ignored) {
            return null;
        }
    }

    private Double doubleValue(Object value) {
        if (value == null) {
            return null;
        }
        if (value instanceof Number number) {
            return number.doubleValue();
        }
        try {
            return Double.parseDouble(String.valueOf(value));
        } catch (NumberFormatException ignored) {
            return null;
        }
    }

    private void sendResponseChunk(WebSocketSession session, String chunk) {
        try {
            // 检查是否需要停止发送
            if (Boolean.TRUE.equals(stopFlags.get(session.getId()))) {
                logger.debug("检测到停止标志，跳过发送响应块");
                return;
            }
            
            // 将chunk包装成JSON格式，匹配前端期望的数据结构
            Map<String, String> chunkResponse = Map.of("chunk", chunk);
            String jsonChunk = objectMapper.writeValueAsString(chunkResponse);
            logger.debug("发送响应块到会话 {}: {}", session.getId(), jsonChunk);
            session.sendMessage(new TextMessage(jsonChunk));
        } catch (Exception e) {
            logger.error("发送响应块失败: {}", e.getMessage(), e);
        }
    }

    private void sendResponseChunks(WebSocketSession session, String content) {
        if (content == null || content.isEmpty()) {
            return;
        }
        for (int start = 0; start < content.length(); start += STREAM_CHUNK_SIZE) {
            if (Boolean.TRUE.equals(stopFlags.get(session.getId()))) {
                logger.debug("检测到停止标志，终止分块发送");
                return;
            }
            int end = Math.min(content.length(), start + STREAM_CHUNK_SIZE);
            sendResponseChunk(session, content.substring(start, end));
            try {
                Thread.sleep(STREAM_CHUNK_DELAY_MS);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                return;
            }
        }
    }

    private void sendCompletionNotification(WebSocketSession session) {
        try {
            long currentTime = System.currentTimeMillis();
            Map<String, Object> notification = Map.of(
                "type", "completion",
                "status", "finished", 
                "message", "响应已完成",
                "timestamp", currentTime,
                "date", java.time.LocalDateTime.now().toString()
            );
            String notificationJson = objectMapper.writeValueAsString(notification);
            logger.info("发送完成通知到会话 {}: {}", session.getId(), notificationJson);
            session.sendMessage(new TextMessage(notificationJson));
            logger.info("已发送响应完成通知到会话: {}", session.getId());
        } catch (Exception e) {
            logger.error("发送完成通知失败: {}", e.getMessage(), e);
        }
    }

    private void handleError(WebSocketSession session, Throwable error) {
        logger.error("AI服务错误: {}", error.getMessage(), error);
        try {
            Map<String, String> errorResponse = Map.of("error", "AI服务暂时不可用，请稍后重试");
            String errorJson = objectMapper.writeValueAsString(errorResponse);
            logger.error("发送错误消息到会话 {}: {}", session.getId(), errorJson);
            session.sendMessage(new TextMessage(errorJson));
            logger.error("已发送错误消息到会话: {}", session.getId());
        } catch (Exception e) {
            logger.error("发送错误消息失败: {}", e.getMessage(), e);
        }
    }

    private void sendRateLimitMessage(WebSocketSession session, RateLimitExceededException exception) {
        try {
            Map<String, Object> response = Map.of(
                    "code", 429,
                    "message", exception.getMessage(),
                    "retryAfterSeconds", exception.getRetryAfterSeconds()
            );
            session.sendMessage(new TextMessage(objectMapper.writeValueAsString(response)));
        } catch (Exception e) {
            logger.error("发送限流消息失败: {}", e.getMessage(), e);
        }
    }

    /**
     * 停止响应
     */
    public void stopResponse(String userId, WebSocketSession session) {
        String sessionId = session.getId();
        logger.info("收到停止请求，用户ID: {}, 会话ID: {}", userId, sessionId);

        // 设置停止标志
        stopFlags.put(sessionId, true);

        // 发送停止确认
        try {
            long currentTime = System.currentTimeMillis();
            Map<String, Object> response = Map.of(
                "type", "stop",
                "message", "响应已停止",
                "timestamp", currentTime,
                "date", java.time.Instant.ofEpochMilli(currentTime).toString()
            );
            String stopJson = objectMapper.writeValueAsString(response);
            logger.info("发送停止确认到会话 {}: {}", sessionId, stopJson);
            session.sendMessage(new TextMessage(stopJson));
            logger.info("已发送停止确认，会话ID: {}", sessionId);
        } catch (Exception e) {
            logger.error("发送停止确认失败: {}", e.getMessage(), e);
        }

        // 清理停止标志（延迟清理，避免影响当前响应）
        try {
            chatMonitorExecutor.execute(() -> {
                try {
                    Thread.sleep(2000);
                    stopFlags.remove(sessionId);
                    logger.debug("已清理停止标志，会话ID: {}", sessionId);
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                }
            });
        } catch (RejectedExecutionException ignore) {
            stopFlags.remove(sessionId);
        }
    }

    /**
     * 根据会话ID和引用编号获取文件MD5
     *
     * @param sessionId WebSocket会话ID
     * @param referenceNumber 引用编号
     * @return 文件MD5，如果找不到则返回null
     */
    public String getReferenceMd5(String sessionId, int referenceNumber) {
        ReferenceInfo detail = getReferenceDetail(sessionId, referenceNumber);
        return detail != null ? detail.fileMd5() : null;
    }

    public ReferenceInfo getReferenceDetail(String sessionId, int referenceNumber) {
        logger.info("查询引用MD5: sessionId={}, referenceNumber=#{}", sessionId, referenceNumber);

        Map<Integer, ReferenceInfo> referenceMapping = sessionReferenceMappings.get(sessionId);
        if (referenceMapping == null) {
            logger.error("未找到会话 {} 的引用映射，当前所有会话: {}", sessionId, sessionReferenceMappings.keySet());
            return null;
        }

        logger.info("会话 {} 的引用映射内容: {}", sessionId, referenceMapping);

        ReferenceInfo detail = referenceMapping.get(referenceNumber);
        if (detail == null) {
            logger.error("会话 {} 中未找到引用编号 #{}, 可用的引用编号: {}", sessionId, referenceNumber, referenceMapping.keySet());
            return null;
        }

        logger.info("成功找到引用映射: sessionId={}, referenceNumber=#{}, fileMd5={}, pageNumber={}",
                sessionId, referenceNumber, detail.fileMd5(), detail.pageNumber());
        return detail;
    }

    private String buildRetrievalLabel(String retrievalMode) {
        if ("TEXT_ONLY".equalsIgnoreCase(retrievalMode)) {
            return "关键词召回";
        }
        if ("VECTOR".equalsIgnoreCase(retrievalMode)) {
            return "向量召回";
        }
        return "混合召回（语义相关 + 关键词命中）";
    }

    private String buildEvidenceSnippet(String userMessage, String anchorText, String matchedChunkText) {
        String normalizedAnchorText = normalizeEvidenceText(anchorText);
        if (!normalizedAnchorText.isBlank()) {
            return trimToMaxLength(normalizedAnchorText, MAX_EVIDENCE_SNIPPET_LEN);
        }

        String normalizedMatchedChunk = normalizeEvidenceText(matchedChunkText);
        if (normalizedMatchedChunk.isBlank()) {
            String normalizedUserMessage = normalizeEvidenceText(userMessage);
            if (!normalizedUserMessage.isBlank()) {
                return trimToMaxLength(normalizedUserMessage, MAX_EVIDENCE_SNIPPET_LEN);
            }
            return "";
        }

        String[] sentences = normalizedMatchedChunk.split("(?<=[。！？!?；;])");
        for (String sentence : sentences) {
            String trimmedSentence = sentence.trim();
            if (trimmedSentence.length() >= 12) {
                return trimToMaxLength(trimmedSentence, MAX_EVIDENCE_SNIPPET_LEN);
            }
        }

        return trimToMaxLength(normalizedMatchedChunk, MAX_EVIDENCE_SNIPPET_LEN);
    }

    private String trimToMaxLength(String value, int maxLength) {
        String normalized = normalizeEvidenceText(value);
        if (normalized.length() <= maxLength) {
            return normalized;
        }
        return normalized.substring(0, maxLength) + "…";
    }

    private String normalizeEvidenceText(String value) {
        return value == null ? "" : value.replaceAll("\\s+", " ").trim();
    }

    /**
     * 清理会话的引用映射
     *
     * @param sessionId WebSocket会话ID
     */
    public void clearSessionReferenceMapping(String sessionId) {
        Map<Integer, ReferenceInfo> removed = sessionReferenceMappings.remove(sessionId);
        if (removed != null) {
            logger.info("清理会话 {} 的引用映射，共 {} 条", sessionId, removed.size());
        }
    }

    public record ReferenceInfo(
            String fileMd5,
            String fileName,
            Integer pageNumber,
            String anchorText,
            String retrievalMode,
            String retrievalLabel,
            String retrievalQuery,
            String matchedChunkText,
            String evidenceSnippet,
            Double score,
            Integer chunkId
    ) {
    }
}
